"""empty message

Revision ID: cd155faab651
Revises: d0b7154054df
Create Date: 2024-01-25 21:22:12.125370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd155faab651'
down_revision = 'd0b7154054df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resort', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accommodations', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('dining', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('fitness_wellness', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('business_facilities', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('concierge_services', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('entertainment', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('additional_services', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('security', sa.String(length=100), nullable=True))
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.drop_column('amenities')
        batch_op.drop_column('description')
        batch_op.drop_column('special_services')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resort', schema=None) as batch_op:
        batch_op.add_column(sa.Column('special_services', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('amenities', sa.TEXT(), nullable=True))
        batch_op.alter_column('location',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.drop_column('security')
        batch_op.drop_column('additional_services')
        batch_op.drop_column('entertainment')
        batch_op.drop_column('concierge_services')
        batch_op.drop_column('business_facilities')
        batch_op.drop_column('fitness_wellness')
        batch_op.drop_column('dining')
        batch_op.drop_column('accommodations')

    # ### end Alembic commands ###
