"""empty message

Revision ID: d0b7154054df
Revises: 98f3aca2c5e9
Create Date: 2024-01-25 18:24:42.491133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0b7154054df'
down_revision = '98f3aca2c5e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('residence', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('joining_year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_picture')
        batch_op.drop_column('joining_year')
        batch_op.drop_column('residence')
        batch_op.drop_column('gender')
        batch_op.drop_column('age')
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
